//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_booking_RPCYYH {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cinema_booking_RPCYYH.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moziműsor mentése.
        /// </summary>
        internal static string Form1_Button1 {
            get {
                return ResourceManager.GetString("Form1_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helyfoglalás.
        /// </summary>
        internal static string Form1_Button2 {
            get {
                return ResourceManager.GetString("Form1_Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlahaMozi Jegyfoglalás.
        /// </summary>
        internal static string Form1_MainTitle {
            get {
                return ResourceManager.GetString("Form1_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film kiválasztása:.
        /// </summary>
        internal static string Form1_Subtitle1 {
            get {
                return ResourceManager.GetString("Form1_Subtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Időpont kiválasztása:.
        /// </summary>
        internal static string Form1_Subtitle2 {
            get {
                return ResourceManager.GetString("Form1_Subtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szabad helyek:.
        /// </summary>
        internal static string Form1_Subtitle3 {
            get {
                return ResourceManager.GetString("Form1_Subtitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szűrők:.
        /// </summary>
        internal static string Form1_Subtitle4 {
            get {
                return ResourceManager.GetString("Form1_Subtitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foglalás.
        /// </summary>
        internal static string MB_Button1 {
            get {
                return ResourceManager.GetString("MB_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissza.
        /// </summary>
        internal static string MB_Button2 {
            get {
                return ResourceManager.GetString("MB_Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Részletek.
        /// </summary>
        internal static string MB_MainTitle {
            get {
                return ResourceManager.GetString("MB_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film:.
        /// </summary>
        internal static string MB_Subtitle1 {
            get {
                return ResourceManager.GetString("MB_Subtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Időpont:.
        /// </summary>
        internal static string MB_Subtitle2 {
            get {
                return ResourceManager.GetString("MB_Subtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Összes szék száma:.
        /// </summary>
        internal static string MB_Subtitle3 {
            get {
                return ResourceManager.GetString("MB_Subtitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szabad székek száma:.
        /// </summary>
        internal static string MB_Subtitle4 {
            get {
                return ResourceManager.GetString("MB_Subtitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Véglegesítés.
        /// </summary>
        internal static string UC_Button1 {
            get {
                return ResourceManager.GetString("UC_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foglalási adatok.
        /// </summary>
        internal static string UC_MainTitle1 {
            get {
                return ResourceManager.GetString("UC_MainTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foglalási összesítő.
        /// </summary>
        internal static string UC_MainTitle2 {
            get {
                return ResourceManager.GetString("UC_MainTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Teljes név:.
        /// </summary>
        internal static string UC_Subtitle1 {
            get {
                return ResourceManager.GetString("UC_Subtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Email cím:.
        /// </summary>
        internal static string UC_Subtitle2 {
            get {
                return ResourceManager.GetString("UC_Subtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Telefonszám:.
        /// </summary>
        internal static string UC_Subtitle3 {
            get {
                return ResourceManager.GetString("UC_Subtitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formátum: 06/30-000-0000.
        /// </summary>
        internal static string UC_Subtitle4 {
            get {
                return ResourceManager.GetString("UC_Subtitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jegyek száma:.
        /// </summary>
        internal static string UC_Subtitle5 {
            get {
                return ResourceManager.GetString("UC_Subtitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teljes összeg:.
        /// </summary>
        internal static string UC_Subtitle6 {
            get {
                return ResourceManager.GetString("UC_Subtitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film:.
        /// </summary>
        internal static string UC_Subtitle7 {
            get {
                return ResourceManager.GetString("UC_Subtitle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Időpont:.
        /// </summary>
        internal static string UC_Subtitle8 {
            get {
                return ResourceManager.GetString("UC_Subtitle8", resourceCulture);
            }
        }
    }
}
