//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_booking_RPCYYH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Ticket_ID { get; set; }
        public int Movie_Show_FK { get; set; }
        public int Seat_FK { get; set; }
        public int Booking_FK { get; set; }
        public decimal Price { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Movie_Show Movie_Show { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
